namespace CliWrap.Models
{
    /// <summary>
    /// Output generated by executing a command line interface
    /// </summary>
    public class ExecutionOutput
    {
        /// <summary>
        /// Exit code
        /// </summary>
        public int ExitCode { get; }

        /// <summary>
        /// Standard output
        /// </summary>
        public string StandardOutput { get; }

        /// <summary>
        /// Standard error
        /// </summary>
        public string StandardError { get; }

        /// <inheritdoc />
        public ExecutionOutput(int exitCode, string standardOutput, string standardError)
        {
            ExitCode = exitCode;
            StandardOutput = standardOutput;
            StandardError = standardError;
        }
    }
}